on: [push, pull_request]
name: Coverage
jobs:
  coveralls:
    name: data-interval
    runs-on: ${{ matrix.os }}
    env:
      STACK_YAML: ${{ matrix.stack_yaml }}
    strategy:
      matrix:
        include:
          - ghc: '8.10.2'
            os: ubuntu-latest
            stack_yaml: 'stack-8.10.2.yaml'
            flags: ''
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
          stack-setup-ghc: true

      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Build
        run: stack build --test --no-run-tests --coverage ${{ matrix.flags }}

      - name: Test
        run: stack test --coverage ${{ matrix.flags }}

      - name: Coveralls
        continue-on-error: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          curl -L https://github.com/lehins/stack-hpc-coveralls/releases/download/v0.0.6.0/shc.tar.gz | tar xz shc
          ./shc --repo-token="$COVERALLS_REPO_TOKEN" data-interval test-interval
